In [1]:
from bs4 import BeautifulSoup
import requests

# Question: 4

In [2]:
page = requests.get('https://www.bewakoof.com/bestseller?sort=popular%20')

page

In [43]:
# soup = BeautifulSoup(page.content)

# soup

In [4]:
item = []

for i in soup.find_all('h2',class_="clr-shade4 h3-p-name undefined false"):
    item.append(i.text)
    
item

["Women's Blue Round in Bugs Graphic Printed Oversized Short Top",
 "Women's Blue Inner Peace Graphic Printed Boyfriend T-shirt",
 "Men's Black Create Good Stories Typography T-shirt",
 "Men's Black T-shirt",
 "Women's Blue Hello Sunshine Graphic Printed Boyfriend T-shirt",
 "Men's Jet Black Vest",
 "Men's Black Iron Man of War Graphic Printed Vest",
 "Men's White T-shirt",
 "Men's Red T-shirt",
 "Women's Grey Oversized Acid Wash T-shirt"]

In [5]:
price = []

for i in soup.find_all('div',class_="discountedPriceText clr-p-black false"):
    price.append(i.text.replace('â‚¹','Rs.'))
    
price

['Rs.487',
 'Rs.389',
 'Rs.369',
 'Rs.599',
 'Rs.379',
 'Rs.409',
 'Rs.499',
 'Rs.469',
 'Rs.609',
 'Rs.399']

In [6]:
image = []

for i in soup.find_all('img',class_="productImgTag"):
    image.append(i['src'])
    
image

['https://images.bewakoof.com/t640/women-s-blue-round-in-bugs-graphic-printed-oversized-short-top-589789-1707221362-1.jpg',
 'https://images.bewakoof.com/t640/women-s-blue-inner-peace-graphic-printed-boyfriend-t-shirt-295707-1695391077-1.jpg',
 'https://images.bewakoof.com/t640/men-s-black-create-good-stories-typography-t-shirt-283013-1715257551-1.jpg',
 'https://images.bewakoof.com/t640/men-s-black-t-shirt-106-1701423878-1.jpg',
 'https://images.bewakoof.com/t640/hello-sunshine-boyfriend-t-shirt-navy-blue-296647-1655748887-1.jpg',
 'https://images.bewakoof.com/t640/jet-black-vest-210687-1659522825-1.jpg',
 'https://images.bewakoof.com/t640/iron-man-of-war-vest-avl-220651-1655748304-1.jpg',
 'https://images.bewakoof.com/t640/men-s-white-t-shirt-105-1702967985-1.jpg',
 'https://images.bewakoof.com/t640/men-s-red-t-shirt-69875-1709214978-1.jpg',
 'https://images.bewakoof.com/t640/women-grey-solid-tshirt-24-582039-1688996135-1.jpg']

In [7]:
import pandas as pd

In [8]:
df = pd.DataFrame({'Product':item,'Price':price,'Image-URL':image})

df

,Product,Price,Image-URL
0,Women's Blue Round in Bugs Graphic Printed Ove...,Rs.487,https://images.bewakoof.com/t640/women-s-blue-...
1,Women's Blue Inner Peace Graphic Printed Boyfr...,Rs.389,https://images.bewakoof.com/t640/women-s-blue-...
2,Men's Black Create Good Stories Typography T-s...,Rs.369,https://images.bewakoof.com/t640/men-s-black-c...
3,Men's Black T-shirt,Rs.599,https://images.bewakoof.com/t640/men-s-black-t...
4,Women's Blue Hello Sunshine Graphic Printed Bo...,Rs.379,https://images.bewakoof.com/t640/hello-sunshin...
5,Men's Jet Black Vest,Rs.409,https://images.bewakoof.com/t640/jet-black-ves...
6,Men's Black Iron Man of War Graphic Printed Vest,Rs.499,https://images.bewakoof.com/t640/iron-man-of-w...
7,Men's White T-shirt,Rs.469,https://images.bewakoof.com/t640/men-s-white-t...
8,Men's Red T-shirt,Rs.609,https://images.bewakoof.com/t640/men-s-red-t-s...
9,Women's Grey Oversized Acid Wash T-shirt,Rs.399,https://images.bewakoof.com/t640/women-grey-so...

# Question : 5

In [9]:
res = requests.get('https://www.cnbc.com/world/?region=world')

res

In [44]:
# soup = BeautifulSoup(res.content, 'html.parser')
# soup

In [11]:
news = []

for i in soup.find_all('a',class_="LatestNews-headline"):
    news.append(i.text)
    
news

['Report: These cereals have the most fiber, protein and other essential nutrients',
 'Why a couple saving for a home in Chicago bought one in Italy instead ',
 'What we expect from Costco earnings and 3 others, and Fed favorite inflation gauge',
 "Here's what it's like inside the operating room when someone gets a brain implant",
 "Couple earns $270,000 a year, but doesn't feel like it's enough",
 'How digital health companies are capitalizing on the GLP-1 boom',
 'Collectors may pay thousands for $1 bills with this printing errorâ€”how to check',
 "'Pregnancy discrimination across corporate America is still rampant': author ",
 "Self-made millionaire: This simple 3-word question can 'change your life'",
 'Rise of resort day passes offers travelers luxury on a budget',
 'Angela Bassett: My mom used this 5-word phrase to raise successful children',
 "The Fed probably won't be delivering any interest rate cuts this summer ",
 'This power management stock could win big from AI-fueled energy demands',
 "Morgan Stanley's top travel stocks amid high-end consumer demand this summer ",
 'Keep buying top stocks like Nvidia ahead of summer, Morgan Stanley says',
 'Texas Republicans confab hints at fallout from GOP breakup with corporate America',
 "Cramer's week ahead: Earnings from Costco, Dell, Ulta and Dollar General",
 "Cramer's Lighting Round: Sell AMC",
 "After a better-than-expected quarter, Cramer is optimistic on Macy's turnaround",
 'Truth Social struggles to grow U.S. user base, new data on Trump Media app shows',
 "FDIC watchdog: Allegations of misconduct were not reported 'in a timely manner'",
 'UAW challenges Mercedes-Benz union vote, asks NLRB for new election',
 'Buy quality tech stocks that are immune to high inflation and rates, Trivariate Research says ',
 'Markets see inflation as key in keeping stocks at their record highs',
 'Two CVS retail stores in Rhode Island join new national pharmacy union',
 "Here's where BlackRock's bond guru Rick Rieder sees opportunity right now",
 'Boeing, NASA say Starliner astronaut launch will move forward despite leak',
 'Stocks making the biggest moves midday: Workday, Lucid, Toast, Deckers and more',
 'Jim Cramer says Nike should watch its back with Hoka running shoes doing so well',
 'Moderna and this solar name are among the most overbought stocks']

In [12]:
links = []

for i in soup.find_all('a',class_="LatestNews-headline"):
    links.append(i['href'])
        
links

['https://www.cnbc.com/2024/05/25/these-cereals-have-the-most-fiber-protein-and-other-essential-nutrients.html',
 'https://www.cnbc.com/2024/05/25/couple-saving-first-us-home-bought-italy-instead.html',
 'https://www.cnbc.com/2024/05/25/costco-earnings-and-3-others-and-the-fed-favorite-inflation-gauge.html',
 'https://www.cnbc.com/2024/05/25/neuralink-competitor-precision-neuroscience-is-testing-its-brain-implant-in-humans.html',
 'https://www.cnbc.com/2024/05/25/debt-free-couple-earning-six-figures-doesnt-feel-like-its-enough.html',
 'https://www.cnbc.com/2024/05/25/digital-health-companies-are-launching-programs-around-glp-1s-.html',
 'https://www.cnbc.com/2024/05/25/collectors-may-pay-thousands-for-dollar-bills-with-printing-error.html',
 'https://www.cnbc.com/2024/05/25/pregnancy-discrimination-still-rampant-in-corporate-america-author.html',
 'https://www.cnbc.com/2024/05/25/rse-ventures-ceo-matt-higgins-use-this-question-to-fight-imposter-syndrome.html',
 'https://www.cnbc.com/2024/05/25/resort-day-passes.html',
 'https://www.cnbc.com/2024/05/25/angela-bassett-my-mom-used-this-phrase-to-raise-successful-children.html',
 'https://www.cnbc.com/2024/05/25/the-fed-probably-wont-deliver-any-interest-rate-cuts-this-summer-.html',
 'https://www.cnbc.com/2024/05/25/this-power-management-stock-could-win-big-from-ai-fueled-energy-demands.html',
 'https://www.cnbc.com/2024/05/25/summer-travel-stocks.html',
 'https://www.cnbc.com/2024/05/25/tech-stocks-like-nvidia-are-heating-up.html',
 'https://www.cnbc.com/2024/05/24/trump-republican-convention-splits-with-corporate-sponsors-.html',
 'https://www.cnbc.com/2024/05/24/costco-dell-ulta-and-dollar-general-earnings.html',
 'https://www.cnbc.com/2024/05/24/cramers-lighting-round-sell-amc.html',
 'https://www.cnbc.com/2024/05/24/after-a-better-than-expected-quarter-cramers-optimistic-on-macys.html',
 'https://www.cnbc.com/2024/05/24/truth-social-traffic-trump-media-djt-data.html',
 'https://www.cnbc.com/2024/05/24/fdic-watchdog-senior-officials-misconduct-allegations-not-reported-promptly.html',
 'https://www.cnbc.com/2024/05/24/uaw-mercedes-benz-challenge.html',
 'https://www.cnbc.com/2024/05/24/buy-quality-tech-stocks-immune-to-high-inflation-and-rates-trivariate-research-says-.html',
 'https://www.cnbc.com/2024/05/24/the-key-for-markets-next-week-will-be-inflation-as-stocks-try-to-maintain-record-highs.html',
 'https://www.cnbc.com/2024/05/24/two-cvs-pharmacies-join-new-national-pharmacy-union.html',
 'https://www.cnbc.com/2024/05/24/where-blackrocks-rick-rieder-sees-opportunity-right-now.html',
 'https://www.cnbc.com/2024/05/24/boeing-nasa-starliner-astronaut-launch-moving-forward.html',
 'https://www.cnbc.com/2024/05/24/stocks-making-the-biggest-moves-midday-wday-lcid-tost-deck.html',
 'https://www.cnbc.com/2024/05/24/jim-cramer-nike-should-watch-out-with-hoka-running-shoes-doing-so-well.html',
 'https://www.cnbc.com/2024/05/24/mrna-is-among-the-most-overbought-stocks-after-a-record-setting-week.html']

In [13]:
time = []

for i in soup.find_all('time',class_="LatestNews-timestamp"):
    time.append(i.text)
    
time

['14 Hours Ago',
 '14 Hours Ago',
 '15 Hours Ago',
 '15 Hours Ago',
 '15 Hours Ago',
 '16 Hours Ago',
 '16 Hours Ago',
 '16 Hours Ago',
 '16 Hours Ago',
 '17 Hours Ago',
 '17 Hours Ago',
 '17 Hours Ago',
 '17 Hours Ago',
 '17 Hours Ago',
 '17 Hours Ago',
 'May 24, 2024',
 'May 24, 2024',
 'May 24, 2024',
 'May 24, 2024',
 'May 24, 2024',
 'May 24, 2024',
 'May 24, 2024',
 'May 24, 2024',
 'May 24, 2024',
 'May 24, 2024',
 'May 24, 2024',
 'May 24, 2024',
 'May 24, 2024',
 'May 24, 2024',
 'May 24, 2024']

In [14]:
df = pd.DataFrame({'Headlines':news,'Release':time,'News-Link':links})

df

,Headlines,Release,News-Link
0,"Report: These cereals have the most fiber, pro...",14 Hours Ago,https://www.cnbc.com/2024/05/25/these-cereals-...
1,Why a couple saving for a home in Chicago boug...,14 Hours Ago,https://www.cnbc.com/2024/05/25/couple-saving-...
2,What we expect from Costco earnings and 3 othe...,15 Hours Ago,https://www.cnbc.com/2024/05/25/costco-earning...
3,Here's what it's like inside the operating roo...,15 Hours Ago,https://www.cnbc.com/2024/05/25/neuralink-comp...
4,"Couple earns $270,000 a year, but doesn't feel...",15 Hours Ago,https://www.cnbc.com/2024/05/25/debt-free-coup...
5,How digital health companies are capitalizing ...,16 Hours Ago,https://www.cnbc.com/2024/05/25/digital-health...
6,Collectors may pay thousands for $1 bills with...,16 Hours Ago,https://www.cnbc.com/2024/05/25/collectors-may...
7,'Pregnancy discrimination across corporate Ame...,16 Hours Ago,https://www.cnbc.com/2024/05/25/pregnancy-disc...
8,Self-made millionaire: This simple 3-word ques...,16 Hours Ago,https://www.cnbc.com/2024/05/25/rse-ventures-c...
9,Rise of resort day passes offers travelers lux...,17 Hours Ago,https://www.cnbc.com/2024/05/25/resort-day-pas...
10,Angela Bassett: My mom used this 5-word phrase...,17 Hours Ago,https://www.cnbc.com/2024/05/25/angela-bassett...
11,The Fed probably won't be delivering any inter...,17 Hours Ago,https://www.cnbc.com/2024/05/25/the-fed-probab...
12,This power management stock could win big from...,17 Hours Ago,https://www.cnbc.com/2024/05/25/this-power-man...
13,Morgan Stanley's top travel stocks amid high-e...,17 Hours Ago,https://www.cnbc.com/2024/05/25/summer-travel-...
14,Keep buying top stocks like Nvidia ahead of su...,17 Hours Ago,https://www.cnbc.com/2024/05/25/tech-stocks-li...
15,Texas Republicans confab hints at fallout from...,"May 24, 2024",https://www.cnbc.com/2024/05/24/trump-republic...
16,"Cramer's week ahead: Earnings from Costco, Del...","May 24, 2024",https://www.cnbc.com/2024/05/24/costco-dell-ul...
17,Cramer's Lighting Round: Sell AMC,"May 24, 2024",https://www.cnbc.com/2024/05/24/cramers-lighti...
18,"After a better-than-expected quarter, Cramer i...","May 24, 2024",https://www.cnbc.com/2024/05/24/after-a-better...
19,"Truth Social struggles to grow U.S. user base,...","May 24, 2024",https://www.cnbc.com/2024/05/24/truth-social-t...
20,FDIC watchdog: Allegations of misconduct were ...,"May 24, 2024",https://www.cnbc.com/2024/05/24/fdic-watchdog-...
21,"UAW challenges Mercedes-Benz union vote, asks ...","May 24, 2024",https://www.cnbc.com/2024/05/24/uaw-mercedes-b...
22,Buy quality tech stocks that are immune to hig...,"May 24, 2024",https://www.cnbc.com/2024/05/24/buy-quality-te...
23,Markets see inflation as key in keeping stocks...,"May 24, 2024",https://www.cnbc.com/2024/05/24/the-key-for-ma...
24,Two CVS retail stores in Rhode Island join new...,"May 24, 2024",https://www.cnbc.com/2024/05/24/two-cvs-pharma...
25,Here's where BlackRock's bond guru Rick Rieder...,"May 24, 2024",https://www.cnbc.com/2024/05/24/where-blackroc...
26,"Boeing, NASA say Starliner astronaut launch wi...","May 24, 2024",https://www.cnbc.com/2024/05/24/boeing-nasa-st...
27,Stocks making the biggest moves midday: Workda...,"May 24, 2024",https://www.cnbc.com/2024/05/24/stocks-making-...
28,Jim Cramer says Nike should watch its back wit...,"May 24, 2024",https://www.cnbc.com/2024/05/24/jim-cramer-nik...
29,Moderna and this solar name are among the most...,"May 24, 2024",https://www.cnbc.com/2024/05/24/mrna-is-among-...

# Question : 6

In [15]:
source = requests.get('https://www.keaipublishing.com/en/journals/artificial-intelligence-in-agriculture/most-downloaded-articles/')

source

In [45]:
# soup = BeautifulSoup(source.content)

# soup

In [17]:
titles = []

for i in soup.find_all('h2',class_="h5 article-title"):
    titles.append(i.text[23:155])
    
titles

['Implementation of artificial intelligence in agriculture for optimisation of irrigation and application of pesticides and herbicides',
 'Review of agricultural IoT technology\r\n                \n',
 'A comprehensive review on automation in agriculture using artificial intelligence\r\n                \n',
 'Automation and digitization of agriculture using artificial intelligence and internet of things\r\n                \n',
 'Real-time hyperspectral imaging for the in-field estimation of strawberry ripeness with deep learning\r\n                \n',
 'A review of imaging techniques for plant disease detection\r\n                \n',
 'Deep learning based computer vision approaches for smart agricultural applications\r\n                \n',
 'Applications of electronic nose (e-nose) and electronic tongue (e-tongue) in food quality-related properties determination: A review',
 'Fruit ripeness classification: A survey\r\n                \n',
 'How artificial intelligence uses to achieve the agriculture sustainability: Systematic review\r\n                \n',
 'Transfer Learning for Multi-Crop Leaf Disease Image Classification using Convolutional Neural Network VGG\r\n                \n',
 'DeepRice: A deep learning and deep feature based classification of Rice leaf disease subtypes\r\n                \n',
 'Comparison of CNN-based deep learning architectures for rice diseases classification\r\n                \n',
 'Plant disease detection using hybrid model based on convolutional autoencoder and convolutional neural network\r\n                \n',
 'Using an improved lightweight YOLOv8 model for real-time detection of multi-stage apple fruit in complex orchard environments\r\n     ',
 'Deep convolutional neural network models for weed detection in polyhouse grown bell peppers\r\n                \n',
 'A systematic review of machine learning techniques for cattle identification: Datasets, methods and future directions\r\n             ',
 'Examining the interplay between artificial intelligence and the agri-food industry\r\n                \n',
 'Machine learning in nutrient management: A review\r\n                \n',
 'Artificial cognition for applications in smart agriculture: A comprehensive review\r\n                \n',
 'A review on computer vision systems in monitoring of poultry: A welfare perspective\r\n                \n',
 'Machine learning for weedâ€“plant discrimination in agriculture 5.0: An in-depth review\r\n                \n',
 'Automated quality inspection of baby corn using image processing and deep learning\r\n                \n',
 'Explainable artificial intelligence and interpretable machine learning for agricultural data analysis\r\n                \n',
 'LeafSpotNet: A deep learning framework for detecting leaf spot disease in jasmine plants\r\n                \n']

In [18]:
release = [] 

for i in soup.find_all('p',class_="article-date"):
    release.append(i.text)
    
release

['2020',
 '2022',
 'June 2019',
 '2021',
 '2020',
 '2020',
 '2022',
 '2020',
 'March 2023',
 'June 2023',
 '2022',
 'March 2024',
 'September 2023',
 '2021',
 'March 2024',
 '2022',
 '2022',
 '2022',
 'September 2023',
 '2020',
 '2020',
 'December 2023',
 'March 2024',
 '2022',
 'June 2024']

In [19]:
authors = []

for i in soup.find_all('p',class_="article-authors"):
    authors.append(i.text.replace('|',','))
    
authors

[' Tanha Talaviya ,  Dhara Shah ,  Nivedita Patel ,  Hiteshri Yagnik ,  Manan Shah',
 ' Jinyuan Xu ,  Baoxing Gu ,  Guangzhao Tian',
 ' Kirtan Jha ,  Aalap Doshi ,  Poojan Patel ,  Manan Shah',
 ' A. Subeesh ,  C.R. Mehta',
 ' Zongmei Gao ,  Yuanyuan Shao ,  Guantao Xuan ,  Yongxian Wang ,  Yi Liu ,  Xiang Han',
 ' Vijai Singh ,  Namita Sharma ,  Shikha Singh',
 ' V.G. Dhanya ,  A. Subeesh ,  N.L. Kushwaha ,  Dinesh Kumar Vishwakarma ,  T. Nagesh Kumar ,  G. Ritika ,  A.N. Singh',
 ' Juzhong Tan ,  Jie Xu',
 ' Matteo Rizzo ,  Matteo Marcuzzo ,  Alessandro Zangari ,  Andrea Gasparetto ,  Andrea Albarelli',
 ' Vilani Sachithra ,  L.D.C.S. Subhashini',
 ' Ananda S. Paymode ,  Vandana B. Malode',
 ' P. Isaac Ritharson ,  Kumudha Raimond ,  X. Anitha Mary ,  Jennifer Eunice Robert ,  Andrew J',
 ' Md Taimur Ahad ,  Yan Li ,  Bo Song ,  Touhid Bhuiyan',
 ' Punam Bedi ,  Pushkar Gole',
 ' Baoling Ma ,  Zhixin Hua ,  Yuchen Wen ,  Hongxing Deng ,  Yongjie Zhao ,  Liuru Pu ,  Huaibo Song',
 ' A. Subeesh ,  S. Bhole ,  K. Singh ,  N.S. Chandel ,  Y.A. Rajwade ,  K.V.R. Rao ,  S.P. Kumar ,  D. Jat',
 ' Md Ekramul Hossain ,  Muhammad Ashad Kabir ,  Lihong Zheng ,  Dave L. Swain ,  Shawn McGrath ,  Jonathan Medway',
 ' Abderahman Rejeb ,  Karim Rejeb ,  Suhaiza Zailani ,  John G. Keogh ,  Andrea Appolloni',
 ' Oumnia Ennaji ,  Leonardus VergÃ¼tz ,  Achraf El Allali',
 ' Misbah Pathan ,  Nivedita Patel ,  Hiteshri Yagnik ,  Manan Shah',
 ' Cedric Okinda ,  Innocent Nyalala ,  Tchalla Korohou ,  Celestine Okinda ,  Jintao Wang ,  Tracy Achieng ,  Patrick Wamalwa ,  Tai Mang ,  Mingxia Shen',
 ' Filbert H. Juwono ,  W.K. Wong ,  Seema Verma ,  Neha Shekhawat ,  Basil Andy Lease ,  Catur Apriono',
 ' Kris Wonggasem ,  Pongsan Chakranon ,  Papis Wongchaisuwat',
 ' Masahiro Ryo',
 ' Shwetha V ,  Arnav Bhagwat ,  Vijaya Laxmi']

In [20]:
df = pd.DataFrame({'Paper':titles,'Release Year':release,'Authors':authors})

df

,Paper,Release Year,Authors
0,Implementation of artificial intelligence in a...,2020,"Tanha Talaviya , Dhara Shah , Nivedita Pate..."
1,Review of agricultural IoT technology\r\n ...,2022,"Jinyuan Xu , Baoxing Gu , Guangzhao Tian"
2,A comprehensive review on automation in agricu...,June 2019,"Kirtan Jha , Aalap Doshi , Poojan Patel , ..."
3,Automation and digitization of agriculture usi...,2021,"A. Subeesh , C.R. Mehta"
4,Real-time hyperspectral imaging for the in-fie...,2020,"Zongmei Gao , Yuanyuan Shao , Guantao Xuan ..."
5,A review of imaging techniques for plant disea...,2020,"Vijai Singh , Namita Sharma , Shikha Singh"
6,Deep learning based computer vision approaches...,2022,"V.G. Dhanya , A. Subeesh , N.L. Kushwaha , ..."
7,Applications of electronic nose (e-nose) and e...,2020,"Juzhong Tan , Jie Xu"
8,Fruit ripeness classification: A survey\r\n ...,March 2023,"Matteo Rizzo , Matteo Marcuzzo , Alessandro..."
9,How artificial intelligence uses to achieve th...,June 2023,"Vilani Sachithra , L.D.C.S. Subhashini"
10,Transfer Learning for Multi-Crop Leaf Disease ...,2022,"Ananda S. Paymode , Vandana B. Malode"
11,DeepRice: A deep learning and deep feature bas...,March 2024,"P. Isaac Ritharson , Kumudha Raimond , X. A..."
12,Comparison of CNN-based deep learning architec...,September 2023,"Md Taimur Ahad , Yan Li , Bo Song , Touhid..."
13,Plant disease detection using hybrid model bas...,2021,"Punam Bedi , Pushkar Gole"
14,Using an improved lightweight YOLOv8 model for...,March 2024,"Baoling Ma , Zhixin Hua , Yuchen Wen , Hon..."
15,Deep convolutional neural network models for w...,2022,"A. Subeesh , S. Bhole , K. Singh , N.S. Ch..."
16,A systematic review of machine learning techni...,2022,"Md Ekramul Hossain , Muhammad Ashad Kabir , ..."
17,Examining the interplay between artificial int...,2022,"Abderahman Rejeb , Karim Rejeb , Suhaiza Za..."
18,Machine learning in nutrient management: A rev...,September 2023,"Oumnia Ennaji , Leonardus VergÃ¼tz , Achraf ..."
19,Artificial cognition for applications in smart...,2020,"Misbah Pathan , Nivedita Patel , Hiteshri Y..."
20,A review on computer vision systems in monitor...,2020,"Cedric Okinda , Innocent Nyalala , Tchalla ..."
21,Machine learning for weedâ€“plant discrimination...,December 2023,"Filbert H. Juwono , W.K. Wong , Seema Verma..."
22,Automated quality inspection of baby corn usin...,March 2024,"Kris Wonggasem , Pongsan Chakranon , Papis ..."
23,Explainable artificial intelligence and interp...,2022,Masahiro Ryo
24,LeafSpotNet: A deep learning framework for det...,June 2024,"Shwetha V , Arnav Bhagwat , Vijaya Laxmi"

# Question : 3

In [21]:
page = requests.get('https://www.nobroker.in/property/sale/bangalore/multiple?searchParam=W3sibGF0IjoxMi45NzgzNjkyLCJsb24iOjc3LjY0MDgzNTYsInBsYWNlSWQiOiJDaElKa1FOM0dLUVdyanNSTmhCUUpyaEdEN1UiLCJwbGFjZU5hbWUiOiJJbmRpcmFuYWdhciJ9LHsibGF0IjoxMi45OTgxNzMyLCJsb24iOjc3LjU1MzA0NDU5OTk5OTk5LCJwbGFjZUlkIjoiQ2hJSnhmVzREUE05cmpzUktzTlRHLTVwX1FRIiwicGxhY2VOYW1lIjoiUmFqYWppbmFnYXIifSx7ImxhdCI6MTIuOTMwNzczNSwibG9uIjo3Ny41ODM4MzAyLCJwbGFjZUlkIjoiQ2hJSjJkZGxaNWdWcmpzUmgxQk9BYWYtb3JzIiwicGxhY2VOYW1lIjoiSmF5YW5hZ2FyIn1d&radius=2.0&city=bangalore&locality=Indiranagar,Rajajinagar,Jayanagar')

page

In [46]:
# soup = BeautifulSoup(page.content)

# soup

In [23]:
titles = []

for i in soup.find_all('h2',class_="heading-6 flex items-center font-semi-bold m-0"):
    titles.append(i.text)
        
titles

['3 BHK Flat In Silicon Sattva For Sale  In Jayanagar',
 '3 BHK House For Sale  In Agrahara Dasarahalli',
 '3 BHK Apartment In Amarjyothi Apartments For Sale  In Jayanagar 6th Block, Jayanagar',
 '2 BHK House For Sale  In Rajajinagar',
 '4+ BHK House For Sale  In Jayanagar',
 '2 BHK Apartment In Alpine Regency For Sale  In Jayanagar',
 '3 BHK Apartment In Suraj Lakshmi Apartments For Sale  In Basavanagudi',
 '2 BHK Flat In Bindi Sundar Residency For Sale  In Rajajinagar',
 '3 BHK House For Sale  In Jayanagar',
 '3 BHK Flat For Sale  In Rajajinagar',
 '4+ BHK Flat For Sale  In Rdx Studios',
 '3 BHK Flat In Ltg Sr Grand For Sale  In Rajaji Nagar',
 '4+ BHK House For Sale  In Indiranagar',
 '3 BHK House For Sale  In Jayanagar',
 '3 BHK Apartment In Gokul Lake View Apartments For Sale  In Jayanagar',
 '4 BHK House For Sale  In Indiranagar',
 '3 BHK Flat In Santa Clara Apartments For Sale  In Jayanagar',
 '4+ BHK House For Sale  In Indiranagar',
 '4 BHK Flat In Saboori Apartment 751 For Sale  In Shradda Sabori',
 '2 BHK Flat In Gopalkrishna Dhama Apartment For Sale  In Malleshwaram',
 '4 BHK Apartment In Birla Tisya For Sale  In Rajajinagar',
 '3 BHK Apartment In Birla Tisya For Sale  In Rajaji Nagar',
 '3 BHK Apartment In Jayanagar Residency For Sale  In Jayanagar',
 '4+ BHK Apartment In Phoenix Kessaku For Sale  In Rajajinagar',
 '4 BHK Apartment In Phoenix Kessaku For Sale  In Rajajinagar',
 '3 BHK Flat In Silicon Sattva For Sale  In Jayanagar']

In [24]:
loc = []

for i in soup.find_all('div',class_="mt-0.5p overflow-hidden overflow-ellipsis whitespace-nowrap max-w-70 text-gray-light leading-4 po:mb-0.1p po:max-w-95"):
    loc.append(i.text)
    
loc

['4th Main Road, Jayanagar 6th Block,Near Nimishamba Temple',
 'Independent House, near Shell petrol bunk and Raheja Apartments',
 'Amarjyothi Apartments\xa0 Jayanagar 6th block, Bangalore',
 'Independent House, 2nd Stage, near Sri Vani International School',
 'Independent House, No:1,First cross street,RBI colony.Tilak nagar police station',
 'Alpine Regency\xa0  Alpine Regency, 10th D Main Rd, 1st Block, Jaya Nagar East, Jayanagar, Bengaluru, Karnataka 560011, India',
 'Suraj Lakshmi Apartments\xa0 34/1, 1st Main Rd, Tata Silk Farm, Basavanagudi, Bengaluru, Karnataka 560004, India',
 '72nd Cross Rd, 5th Block, Jedara Halli, Rajajinagar, Bengaluru, Karnataka 560023, India',
 'Independent House, 8thmain road 4th cross byrasandra jayanagar 1st block east.',
 'Standalone Building, Near Spandhana nursing home',
 'Standalone Building, Indiranagar ',
 'west of card road near modi hospital ',
 'Independent House, 2nd stage near  Bharat dry fruits and spices',
 'Independent House, 32nd E Cross Road, 4th block Jayanagar Shopping Complex 560041',
 'Gokul Lake View Apartments\xa0 Gokul Lake View Apartments 110/18, 19th Cross Rd 2nd A Main Rd, Jayanagar Bengaluru, Karnataka 560070 India',
 'Independent House,  100 Feet Rd Near New Horizon Public School',
 '3Rd Cross Rd18th main, 9th Block, Marenahalli',
 'Independent House, 101, 10th Cross Road, 1st Stage',
 '37th F Cross Road ,16th Main Road',
 ' Gopalakrishna Dhama Apts, 6th Main Rd, Malleshwara, Bengaluru, Karnataka 560055',
 'Birla Tisya\xa0  Near Sarvodaya College Of Hospital,Magadi Main Road,Rajajinagar,Bangalore',
 'Birla Tisya\xa0  Near Sarvodaya College Of Hospital,Magadi Main Road,Rajajinagar,Bangalore',
 'Jayanagar Residency\xa0 Jayanagar  Jayanagar Residency',
 'Phoenix Kessaku\xa0 Opp. Vivekananda College,Dr Rajkumar Rd,Rajajinagar,Bangalore',
 'Phoenix Kessaku\xa0 Opp. Vivekananda College,Dr Rajkumar Rd,Rajajinagar,Bangalore',
 '4th Main Road, Jayanagar 6th Block,Near Nimishamba Temple']

In [25]:
price = [] 

for i in soup.find_all('div',class_="p-1.5p flex border-b border-b-solid border-cardbordercolor tp:py-1p tp:px-1.5p tp:border-b-0"):
    for j in i.find_all('div',id="minDeposit"):
        for k in j.find_all('div',class_="font-semi-bold heading-6"):
            price.append(k.text.replace('â‚¹','Rs.'))

price

['Rs.1.4 Crores',
 'Rs.1.35 Crores',
 'Rs.1.5 Crores',
 'Rs.1.2 Crores',
 'Rs.5 Crores',
 'Rs.1.65 Crores',
 'Rs.1.2 Crores',
 'Rs.70 Lacs',
 'Rs.1.6 Crores',
 'Rs.1.25 Crores',
 'Rs.4.75 Crores',
 'Rs.2.3 Crores',
 'Rs.3.1 Crores',
 'Rs.2.95 Crores',
 'Rs.1.62 Crores',
 'Rs.3.5 Crores',
 'Rs.1.15 Crores',
 'Rs.7.5 Crores',
 'Rs.1.6 Crores',
 'Rs.1.5 Crores',
 'Rs.3.41 Crores',
 'Rs.2.21 Crores',
 'Rs.2.25 Crores',
 'Rs.11.62 Crores',
 'Rs.9.97 Crores',
 'Rs.1.4 Crores']

In [26]:
emi = []

for i in soup.find_all('div',class_="p-1.5p flex border-b border-b-solid border-cardbordercolor tp:py-1p tp:px-1.5p tp:border-b-0"):
    for j in i.find_all('div',id="roomType"):
        emi.append(j.text.replace('â‚¹','Rs.'))

emi

['Rs.80,240/Month',
 'Rs.77,374/Month',
 'Rs.85,971/Month',
 'Rs.68,777/Month',
 'Rs.2.87 Lacs/Month',
 'Rs.94,568/Month',
 'Rs.68,777/Month',
 'Rs.40,120/Month',
 'Rs.91,703/Month',
 'Rs.71,643/Month',
 'Rs.2.72 Lacs/Month',
 'Rs.1.32 Lacs/Month',
 'Rs.1.78 Lacs/Month',
 'Rs.1.69 Lacs/Month',
 'Rs.92,849/Month',
 'Rs.2.01 Lacs/Month',
 'Rs.65,911/Month',
 'Rs.4.3 Lacs/Month',
 'Rs.91,703/Month',
 'Rs.85,971/Month',
 'Rs.1.95 Lacs/Month',
 'Rs.1.27 Lacs/Month',
 'Rs.1.29 Lacs/Month',
 'Rs.6.66 Lacs/Month',
 'Rs.5.72 Lacs/Month',
 'Rs.80,240/Month']

In [27]:
areas = []

for i in soup.find_all('div',class_="flex flex-col w-33pe items-center tp:w-half po:w-full"):
    for j in i.find_all('div',class_="flex"):
        areas.append(j.text)
    
areas

['1,485 sqft',
 '2,400 sqft',
 '1,552 sqft',
 '1,200 sqft',
 '4,000 sqft',
 '1,320 sqft',
 '1,226 sqft',
 '896 sqft',
 '1,000 sqft',
 '1,050 sqft',
 '3,624 sqft',
 '1,865 sqft',
 '4,800 sqft',
 '1,600 sqft',
 '1,852 sqft',
 '4,800 sqft',
 '1,395 sqft',
 '2,800 sqft',
 '1,800 sqft',
 '1,357 sqft',
 '2,504 sqft',
 '1,657 sqft',
 '2,000 sqft',
 '3,647 sqft',
 '3,147 sqft',
 '1,485 sqft']

In [28]:
import pandas as pd

In [29]:
df = pd.DataFrame({'Title':titles,'Location':loc,'Apartment Price':price,'EMI':emi,'Buildup-Area':areas})

df

,Title,Location,Apartment Price,EMI,Buildup-Area
0,3 BHK Flat In Silicon Sattva For Sale In Jaya...,"4th Main Road, Jayanagar 6th Block,Near Nimish...",Rs.1.4 Crores,"Rs.80,240/Month","1,485 sqft"
1,3 BHK House For Sale In Agrahara Dasarahalli,"Independent House, near Shell petrol bunk and ...",Rs.1.35 Crores,"Rs.77,374/Month","2,400 sqft"
2,3 BHK Apartment In Amarjyothi Apartments For S...,"Amarjyothi ApartmentsÂ Jayanagar 6th block, Ba...",Rs.1.5 Crores,"Rs.85,971/Month","1,552 sqft"
3,2 BHK House For Sale In Rajajinagar,"Independent House, 2nd Stage, near Sri Vani In...",Rs.1.2 Crores,"Rs.68,777/Month","1,200 sqft"
4,4+ BHK House For Sale In Jayanagar,"Independent House, No:1,First cross street,RBI...",Rs.5 Crores,Rs.2.87 Lacs/Month,"4,000 sqft"
5,2 BHK Apartment In Alpine Regency For Sale In...,"Alpine RegencyÂ Alpine Regency, 10th D Main R...",Rs.1.65 Crores,"Rs.94,568/Month","1,320 sqft"
6,3 BHK Apartment In Suraj Lakshmi Apartments Fo...,"Suraj Lakshmi ApartmentsÂ 34/1, 1st Main Rd, T...",Rs.1.2 Crores,"Rs.68,777/Month","1,226 sqft"
7,2 BHK Flat In Bindi Sundar Residency For Sale ...,"72nd Cross Rd, 5th Block, Jedara Halli, Rajaji...",Rs.70 Lacs,"Rs.40,120/Month",896 sqft
8,3 BHK House For Sale In Jayanagar,"Independent House, 8thmain road 4th cross byra...",Rs.1.6 Crores,"Rs.91,703/Month","1,000 sqft"
9,3 BHK Flat For Sale In Rajajinagar,"Standalone Building, Near Spandhana nursing home",Rs.1.25 Crores,"Rs.71,643/Month","1,050 sqft"
10,4+ BHK Flat For Sale In Rdx Studios,"Standalone Building, Indiranagar",Rs.4.75 Crores,Rs.2.72 Lacs/Month,"3,624 sqft"
11,3 BHK Flat In Ltg Sr Grand For Sale In Rajaji...,west of card road near modi hospital,Rs.2.3 Crores,Rs.1.32 Lacs/Month,"1,865 sqft"
12,4+ BHK House For Sale In Indiranagar,"Independent House, 2nd stage near Bharat dry ...",Rs.3.1 Crores,Rs.1.78 Lacs/Month,"4,800 sqft"
13,3 BHK House For Sale In Jayanagar,"Independent House, 32nd E Cross Road, 4th bloc...",Rs.2.95 Crores,Rs.1.69 Lacs/Month,"1,600 sqft"
14,3 BHK Apartment In Gokul Lake View Apartments ...,Gokul Lake View ApartmentsÂ Gokul Lake View Ap...,Rs.1.62 Crores,"Rs.92,849/Month","1,852 sqft"
15,4 BHK House For Sale In Indiranagar,"Independent House, 100 Feet Rd Near New Horiz...",Rs.3.5 Crores,Rs.2.01 Lacs/Month,"4,800 sqft"
16,3 BHK Flat In Santa Clara Apartments For Sale ...,"3Rd Cross Rd18th main, 9th Block, Marenahalli",Rs.1.15 Crores,"Rs.65,911/Month","1,395 sqft"
17,4+ BHK House For Sale In Indiranagar,"Independent House, 101, 10th Cross Road, 1st S...",Rs.7.5 Crores,Rs.4.3 Lacs/Month,"2,800 sqft"
18,4 BHK Flat In Saboori Apartment 751 For Sale ...,"37th F Cross Road ,16th Main Road",Rs.1.6 Crores,"Rs.91,703/Month","1,800 sqft"
19,2 BHK Flat In Gopalkrishna Dhama Apartment For...,"Gopalakrishna Dhama Apts, 6th Main Rd, Malles...",Rs.1.5 Crores,"Rs.85,971/Month","1,357 sqft"
20,4 BHK Apartment In Birla Tisya For Sale In Ra...,Birla TisyaÂ Near Sarvodaya College Of Hospit...,Rs.3.41 Crores,Rs.1.95 Lacs/Month,"2,504 sqft"
21,3 BHK Apartment In Birla Tisya For Sale In Ra...,Birla TisyaÂ Near Sarvodaya College Of Hospit...,Rs.2.21 Crores,Rs.1.27 Lacs/Month,"1,657 sqft"
22,3 BHK Apartment In Jayanagar Residency For Sal...,Jayanagar ResidencyÂ Jayanagar Jayanagar Resi...,Rs.2.25 Crores,Rs.1.29 Lacs/Month,"2,000 sqft"
23,4+ BHK Apartment In Phoenix Kessaku For Sale ...,"Phoenix KessakuÂ Opp. Vivekananda College,Dr R...",Rs.11.62 Crores,Rs.6.66 Lacs/Month,"3,647 sqft"
24,4 BHK Apartment In Phoenix Kessaku For Sale I...,"Phoenix KessakuÂ Opp. Vivekananda College,Dr R...",Rs.9.97 Crores,Rs.5.72 Lacs/Month,"3,147 sqft"
25,3 BHK Flat In Silicon Sattva For Sale In Jaya...,"4th Main Road, Jayanagar 6th Block,Near Nimish...",Rs.1.4 Crores,"Rs.80,240/Month","1,485 sqft"

# Question : 1

In [30]:
page = requests.get('https://www.imdb.com/list/ls056092300/', headers={'User-Agent': 'Mozilla/5.0'})

page

In [47]:
# soup = BeautifulSoup(page.content)

# soup

In [32]:
name = []

for i in soup.find_all('div',class_="ipc-title ipc-title--base ipc-title--title ipc-title-link-no-icon ipc-title--on-textPrimary sc-b189961a-9 iALATN dli-title"):
    for tag in i.find_all('a',class_="ipc-title-link-wrapper"):
        name.append(tag.text[3:])
    
name

['Ship of Theseus',
 'Iruvar',
 'Kaagaz Ke Phool',
 'Lagaan: Once Upon a Time in India',
 'Pather Panchali',
 'Charulata',
 'Rang De Basanti',
 'Dev.D',
 '3 Idiots',
 ' Awaara',
 ' Nayakan',
 ' Aparajito',
 ' Pushpaka Vimana',
 ' Pyaasa',
 ' Ghatashraddha',
 ' Sholay',
 ' Aradhana',
 ' Do Ankhen Barah Haath',
 ' Bombay',
 ' Neecha Nagar',
 ' Do Bigha Zamin',
 ' Garm Hava',
 ' Piravi',
 ' Mughal-E-Azam',
 ' Amma Ariyan',
 ' Madhumati',
 ' Goopy Gyne Bagha Byne',
 ' Gangs of Wasseypur',
 ' Guide',
 ' Satya',
 ' Roja',
 ' Mr. India',
 ' Meghe Dhaka Tara',
 ' Harishchandrachi Factory',
 ' Masoom',
 ' Agneepath',
 ' Tabarana Kathe',
 ' Zakhm',
 ' Dil Chahta Hai',
 ' Bhaag Milkha Bhaag',
 ' Chupke Chupke',
 ' Dilwale Dulhania Le Jayenge',
 ' Taare Zameen Par',
 ' Ardh Satya',
 ' Bhumika',
 ' Enthiran',
 ' Sadma',
 ' Shwaas',
 ' Lamhe',
 ' Haqeeqat',
 ' Shree 420',
 ' Kannathil Muthamittal',
 ' Hum Aapke Hain Koun...!',
 ' Ustad Hotel',
 ' Bandit Queen',
 ' Lakshya',
 ' Black Friday',
 ' Manthan',
 ' Apoorva Raagangal',
 ' English Vinglish',
 ' Jewel Thief',
 ' Pure One',
 ' Maqbool',
 ' Jis Desh Men Ganga Behti Hai',
 ' Sahib Bibi Aur Ghulam',
 ' Shatranj Ke Khilari',
 ' Narthanasala',
 ' Chandni Bar',
 ' Vaaranam Aayiram',
 ' Mr. And Mrs. Iyer',
 ' Chandani',
 ' English, August',
 ' Celluloid',
 ' Salangai Oli',
 ' Munna Bhai M.B.B.S.',
 ' Saaransh',
 ' Guddi',
 ' Vanaja',
 ' Vazhakku Enn 18/9',
 ' Gangaajal',
 ' Angoor',
 ' Guru',
 ' Andaz Apna Apna',
 ' Sangam',
 ' Oka Oori Katha',
 ' Bhuvan Shome',
 ' Border',
 ' Parineeta',
 ' Devdas',
 ' Abohomaan',
 ' Kuch Kuch Hota Hai',
 ' Pithamagan',
 ' Veyyil',
 ' Chemmeen',
 ' Jaane Bhi Do Yaaro',
 ' Apur Sansar',
 ' Kanchivaram',
 ' Monsoon Wedding',
 ' Black',
 '. Deewaar']

In [33]:
year = []

for i in soup.find_all('div',class_="sc-b189961a-0 hBZnfJ"):
    for j in i.find_all('div',class_="sc-b189961a-7 feoqjK dli-title-metadata"):
        year.append(j.text[0:4])
        
year

['2012',
 '1997',
 '1959',
 '2001',
 '1955',
 '1964',
 '2006',
 '2009',
 '2009',
 '1951',
 '1987',
 '1956',
 '1987',
 '1957',
 '1977',
 '1975',
 '1969',
 '1957',
 '1995',
 '1946',
 '1953',
 '1974',
 '1989',
 '1960',
 '1986',
 '1958',
 '1969',
 '2012',
 '1965',
 '1998',
 '1992',
 '1987',
 '1960',
 '2009',
 '1983',
 '1990',
 '1986',
 '1998',
 '2001',
 '2013',
 '1975',
 '1995',
 '2007',
 '1983',
 '1977',
 '2010',
 '1983',
 '2004',
 '1991',
 '1964',
 '1955',
 '2002',
 '1994',
 '2012',
 '1994',
 '2004',
 '2004',
 '1976',
 '1975',
 '2012',
 '1967',
 '1972',
 '2003',
 '1960',
 '1962',
 '1977',
 '1963',
 '2001',
 '2008',
 '2002',
 '1989',
 '1994',
 '2013',
 '1983',
 '2003',
 '1984',
 '1971',
 '2006',
 '2012',
 '2003',
 '1982',
 '2007',
 '1994',
 '1964',
 '1978',
 '1969',
 '1997',
 '2005',
 '1955',
 '2009',
 '1998',
 '2003',
 '2006',
 '1965',
 '1983',
 '1959',
 '2008',
 '2001',
 '2005',
 '1975']

In [34]:
rating = []

for i in soup.find_all('div',class_="sc-e2dbc1a3-0 ajrIH sc-b189961a-2 fkPBP dli-ratings-container"):
    for j in i.find_all('span',class_="ipc-rating-star ipc-rating-star--base ipc-rating-star--imdb ratingGroup--imdb-rating"):
        rating.append(j.text[0:3])
    
rating

['8.0',
 '8.4',
 '7.8',
 '8.1',
 '8.2',
 '8.1',
 '8.1',
 '7.9',
 '8.4',
 '7.8',
 '8.7',
 '8.2',
 '8.6',
 '8.3',
 '7.6',
 '8.1',
 '7.6',
 '8.4',
 '8.1',
 '6.6',
 '8.3',
 '8.0',
 '7.8',
 '8.1',
 '7.4',
 '7.8',
 '8.7',
 '8.2',
 '8.3',
 '8.3',
 '8.1',
 '7.7',
 '7.8',
 '8.4',
 '8.4',
 '7.6',
 '8.1',
 '7.9',
 '8.1',
 '8.2',
 '8.3',
 '8.0',
 '8.3',
 '8.1',
 '7.4',
 '7.1',
 '8.3',
 '8.1',
 '7.2',
 '7.8',
 '7.9',
 '8.3',
 '7.5',
 '8.2',
 '7.5',
 '7.8',
 '8.4',
 '7.7',
 '7.6',
 '7.8',
 '7.9',
 '7.2',
 '8.0',
 '7.1',
 '8.1',
 '7.5',
 '8.1',
 '7.6',
 '8.2',
 '7.9',
 '6.7',
 '7.7',
 '7.7',
 '8.8',
 '8.1',
 '8.1',
 '7.2',
 '7.2',
 '8.2',
 '7.8',
 '8.3',
 '7.7',
 '8.0',
 '7.3',
 '7.8',
 '7.2',
 '7.9',
 '7.2',
 '7.7',
 '7.5',
 '7.5',
 '8.3',
 '7.9',
 '7.7',
 '8.3',
 '8.4',
 '8.2',
 '7.3',
 '8.1',
 '8.0']

In [35]:
import pandas as pd

In [36]:
df = pd.DataFrame({'Title':name,  'Year of Release':year,  'Rating':rating})

df

                                Title Year of Release Rating
0                     Ship of Theseus            2012    8.0
1                              Iruvar            1997    8.4
2                     Kaagaz Ke Phool            1959    7.8
3   Lagaan: Once Upon a Time in India            2001    8.1
4                     Pather Panchali            1955    8.2
..                                ...             ...    ...
95                        Apur Sansar            1959    8.4
96                        Kanchivaram            2008    8.2
97                    Monsoon Wedding            2001    7.3
98                              Black            2005    8.1
99                          . Deewaar            1975    8.0

[100 rows x 3 columns]

# Question : 2

In [37]:
response = requests.get('https://www.patreon.com/coreyms')

response

In [48]:
# soup = BeautifulSoup(response.content, 'html.parser')

# soup

In [39]:
posts = []

for i in soup.find_all('div',class_="sc-bBHxTw iloeMK"):
    for span in i.find_all('span',class_="sc-1cvoi1y-0 hxhWXn"):
        posts.append(j.text)
                
posts

[]

In [40]:
dates = []

for i in soup.find_all('div',class_="sc-lgu5zg-0 dXpjXs"):
    for j in i.find_all('span',class_="sc-1cvoi1y-0 hxhWXn"):
        dates.append(j.text)
                        
dates

[]

In [41]:
likes = []

for i in soup.find_all('div',class_="sc-jrQzAO knZGTZ"):
    likes.append(i.text)
        
likes

[]

In [49]:
df = pd.DataFrame({'Heading':posts,'Date':dates,'Like':likes})

df

Empty DataFrame
Columns: [Heading, Date, Like]
Index: []